#!/bin/bash

. /etc/X11/xinit/xinitrc-common

if [ -x /usr/bin/ck-launch-session -a -z "$XDG_SESSION_COOKIE" -a -z "$CK_XINIT_SESSION" ]; then
    CK_XINIT_SESSION="/usr/bin/ck-launch-session"
fi

XCLIENTS_D=/etc/X11/xinit/Xclients.d
if [ -d "$XCLIENTS_D" -a "$#" -eq 1 -a -x "$XCLIENTS_D/Xclients.$1.sh" ]; then
	exec -l $SHELL -c "$CK_XINIT_SESSION $XCLIENTS_D/Xclients.$1.sh"
fi

if [ $# -eq 1 ]; then
	LXSESSION=$1
else
	LXSESSION=/usr/bin/startlxde
fi

if [ -z "$CK_XINIT_SESSION" ]; then
	exec /bin/sh -c "exec -l $SHELL -c \"$LXSESSION\""
else
	exec -l $SHELL -c "$CK_XINIT_SESSION \"$LXSESSION\""
fi

