#!/bin/sh

[ -f /etc/sysconfig/i18n ] && . /etc/sysconfig/i18n

if [ -z "$LANG" -a -e /etc/sysconfig/language ]; then
	. /etc/sysconfig/language
	if [ -n "$RC_LANG"]; then
		LANG=$RC_LANG
	fi
fi

if [ -n "$LANG" ]; then
	export LANG
fi

exec /usr/bin/lxdm-binary
