#!/bin/bash

if [ $# -eq 1 ]; then
	LXSESSION=$1
else
	LXSESSION=/usr/bin/startlxde
fi

if [ -e /etc/X11/xinit/xinitrc-common ]; then
	. /etc/X11/xinit/xinitrc-common
else
	if [ -r /etc/profile.d/lang.sh ]; then
		. /etc/profile.d/lang.sh
	fi

	userresources=$HOME/.Xresources
	usermodmap=$HOME/.Xmodmap
	userxkbmap=$HOME/.Xkbmap

	sysresources=/etc/X11/Xresources
	sysmodmap=/etc/X11/Xmodmap
	sysxkbmap=/etc/X11/Xkbmap

	# merge in defaults
	[ -r "$sysresources" ] && xrdb -nocpp -merge "$sysresources"
	[ -r "$userresources" ] && xrdb -merge "$userresources"

	# merge in keymaps
	if [ -r "$sysxkbmap" ]; then
		setxkbmap $(cat "$sysxkbmap")
		XKB_IN_USE=yes
	fi

	if [ -r "$userxkbmap" ]; then
		setxkbmap $(cat "$userxkbmap")
		XKB_IN_USE=yes
	fi

	# xkb and xmodmap don't play nice together
	if [ -z "$XKB_IN_USE" ]; then
	    [ -r "$sysmodmap" ] && xmodmap "$sysmodmap"
	    [ -r "$usermodmap" ] && xmodmap "$usermodmap"
	fi
	
	unset XKB_IN_USE
	
	# run all system xinitrc shell scripts.
	if [ -e /etc/X11/xinit/xinitrc.d ]; then
		for file in /etc/X11/xinit/xinitrc.d/* ; do
			if [ -x $file ]; then 
				. $file
			fi
		done
	fi

	if [ -e /etc/X11/xinit.d ]; then
		for file in /etc/X11/xinit.d/* ; do
			if [ -x $file ]; then
				. $file
				echo $file
			fi
		done
	fi
fi

if [ -x /usr/bin/ck-launch-session -a -z "$XDG_SESSION_COOKIE" -a -z "$CK_XINIT_SESSION" ]; then
    CK_XINIT_SESSION="/usr/bin/ck-launch-session"
fi

XCLIENTS_D=/etc/X11/xinit/Xclients.d
if [ -d "$XCLIENTS_D" -a "$#" -eq 1 -a -x "$XCLIENTS_D/Xclients.$1.sh" ]; then
	exec -l $SHELL -c "$CK_XINIT_SESSION $XCLIENTS_D/Xclients.$1.sh"
fi

if [ -z "$CK_XINIT_SESSION" ]; then
	exec /bin/sh -c "exec -l $SHELL -c \"$LXSESSION\""
else
	exec -l $SHELL -c "$CK_XINIT_SESSION \"$LXSESSION\""
fi

